# Generated by Django 4.2.9 on 2024-02-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='unit',
            name='bedroom_type',
            field=models.CharField(choices=[('1BHK', '1 Bedroom, Hall, Kitchen'), ('2BHK', '2 Bedrooms, Hall, Kitchen'), ('3BHK', '3 Bedrooms, Hall, Kitchen'), ('4BHK', '4 Bedrooms, Hall, Kitchen')], default='1BHK', max_length=10),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
