# Generated by Django 4.2.9 on 2024-02-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
